name: Subscription Updater

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * *'

  #workflow_dispatch:
jobs:
  UpdateSub:
    runs-on: ubuntu-latest

    steps:
      - name: Check The Code
        uses: actions/checkout@v2
      - name: Get Files
        run: |
          curl -o 2.txt -LJO https://gen.trexmedia.eu.org/?template=trojan&domain=bexcoders.biz.id&data=https://github.com/exball/sing-box-config/raw/refs/heads/Master/proxy-scaner/rawProxyList.txt
          curl -o 3.txt -LJO https://gen.trexmedia.eu.org/?template=trojan&domain=vpn.stupidworld.web.id&data=https://github.com/exball/sing-box-config/raw/refs/heads/Master/proxy-scaner/rawProxyList.txt
          curl -o 4.txt -LJO https://gen.trexmedia.eu.org/?template=vless&domain=siren.afrcloud.site&data=https://github.com/exball/sing-box-config/raw/refs/heads/Master/proxy-scaner/rawProxyList.txt
          curl -o 5.txt -LJO https://gen.trexmedia.eu.org/?template=vless&domain=world.stupx2.my.id&data=https://github.com/exball/sing-box-config/raw/refs/heads/Master/proxy-scaner/rawProxyList.txt
          curl -o 6.txt -LJO https://gen.trexmedia.eu.org/?template=vless&domain=free.tunneling.dpdns.org&data=https://github.com/exball/sing-box-config/raw/refs/heads/Master/proxy-scaner/rawProxyList.txt
          
      - name: Push And Update Files
        run: |
          git config --global user.name "dinaneq"
          git config --global user.email "dinanda@5412.us.to"
          git add .
          git commit -m "Diperbarui pada - $(TZ='Asia/Jakarta' date '+%Y-%m-%d %H:%M:%S') WIB"
          git push
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-telegram-bot==13.15
          
      - name: Run Python script
        run: |
          python sub.py  # Replace with your script's path
      
      - name: Run Python script
        run: |
          python respon.py  # Replace with your script's path
      
##          curl -o proxylist4.txt -LJO "https://cf.cepu.us.kg/update_proxyip.txt"
##          curl -o proxylist4_$(TZ='Asia/Jakarta' date '+%Y-%m-%d').txt -LJO "https://cf.cepu.us.kg/update_proxyip.txt"
##          curl -o proxylist1.txt -LJO "https://cf.cepu.us.kg/update_proxyip.txt"
##          curl -o proxylist1_$(TZ='Asia/Jakarta' date '+%Y-%m-%d').txt -LJO "https://cf.cepu.us.kg/update_proxyip.txt"
