name: Push to GitHub

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.email "freetomaid@fitrianto.biz.id"
          git config user.name "freetomaid"

      - name: Create version file
        run: echo "1.0.0" > VERSION

      - name: Commit version file
        run: |
          git add .
          git commit -m "Create version file"

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push https://freetomaid:${GH_TOKEN}@github.com/kuysharee/account.git main
